### ISSUE TITLE
ESNRegressor giving IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by conduit242** [TUD-STKS/PyRCN#37]
I'm encountering an error with basic regression over 1D data. It is replicated by:

```
>>> import numpy as np
>>> from pyrcn.echo_state_network import ESNRegressor
>>> x = np.arange(1000)
>>> y = np.random.normal(0, 1, 1000)
>>> reg = ESNRegressor()
>>> reg.fit(X=x.reshape(-1, 1), y=y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/pyrcn/echo_state_network/_esn.py", line 168, in fit
    self._regressor.fit(hidden_layer_state[self.node_to_node.wash_out:, :], y[self.node_to_node.wash_out:, :])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed.
```

Is there something simple here I am missing by chance?

**Comment by renierts** [comment]
If you check out the dev-Branch, it should work now. You can check the new [Jupyter Notebook](https://github.com/TUD-STKS/PyRCN/blob/dev/examples/PyRCN_Intro.ipynb), where the Mackey-Glass timeseries is predicted using the ESNRegressor.
